server:
  port: 8082

spring:
  application:
    name: market.data.service
    exchanges:
      - https://exchange.matraining.com
      - https://exchange2.matraining.com
    stocks:
      - TSLA
      - NFLX
      - ORCL
      - GOOGL
      - AMZN
      - MSFT
      - IBM
      - AAPL
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  data:
    redis:
      host: redis
      port: 6379
      password: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin
    queue: pending-orders-queue
    exchange: main-exchange
    routing-key: order.routing.key
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: "2s"
  cloud:
    discovery:
      enabled: true

openapi:
  service:
    title: market-data-service doc
    version: 1.0.0
    url: http://localhost:8222

springdoc:
  api-docs:
    path: /market-data-service/v3/api-docs
  swagger-ui:
    path: /market-data-service/swagger-ui.html

external:
  exchange1:
    base-url: https://exchange.matraining.com
  exchange2:
    base-url: https://exchange2.matraining.com

eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
eureka.instance.prefer-ip-address: true

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true