services:
  db:
    image: postgres
    container_name: order-service-primary-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: mms-test-local
      PGPORT: 5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

#  app:
#    build: .
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    depends_on:
#      - db