server:
  port: 8222

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: order-manager-route
          uri: lb://order.manager
          predicates:
            - Path=/order-service/v3/api-docs
            - Method=GET
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
            - Method=GET
      discovery:
        locator:
          enable: true
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /order-service/v3/api-docs
        name: Order Service
      - url: /user-service-/v3/api-docs
        name: User Service

jwt:
  secret: SECRET


logging:
  level:
    org.springframework: DEBUG
