services:
  db:
    image: postgres
    container_name: user-primary-db
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: mms-test-local
      PGPORT: 5433