services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_PORT=6379
      - REDIS_DATABASES=market-data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-rc-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  redis_data: